### PR TITLE
Update using-lbaas.md

### PR DESCRIPTION
**Pull request by jbmitch**

### CODE REVIEW

**Comment by llundquist** [comment]
@jbmitch I would prefer to keep the Domain Name variable in the links to console items. Is there a specific reason you wanted to changed these? Are they not working?

**Comment by jbmitch** [comment]
@llundquist That's really strange, I don't remember changing the link like that. All I was wanting to do was add in the External Link icon and the new window tag.

**Comment by llundquist** [comment]
ok, thanks! I can fix it up.

**Comment by llundquist** [comment]
I made this change in another fix. Thanks, Jack, closing this PR.

**Pull request closed without merging**
